git:
    depth: 1
branches:
    only:
        - master
addons:
    apt:
        packages:
            - zsh
#sudo: false
sudo: required
before_script:
    - zsh --version
script:
    - TEST_TARGET=test/all.t make test
